### ISSUE TITLE
deletes only first few lines of css file

### ISSUE THREAD

**Issue by jw-miaem** [kkweon/emacs-css-autoprefixer#2]
Hi, great idea - I just tried running this on a css file and it removed the first couple lines of the css file but no prefixes although it has removed some prefixes manually entered in css

**Comment by kkweon** [comment]
Hi Thanks for reporting. did you install the dependencies?

`npm install -g npx postcss-cli autoprefixer`

**Comment by jw-miaem** [comment]
Yep, can also run from the CLI with: 
npx postcss *.css --use autoprefixer -d build/ 
build contains expected output so my .browserlistrc is also picked up
I'm on mac if that makes any odds?

**Comment by kkweon** [comment]
The behavior of autoprefixer has changed. I could reproduce this after upgrading autoprefixer. 
 Thank you I will fix as soon as I can.

**Comment by kkweon** [comment]
It's weird. After upgrading autoprefixer and postcss-cli, my autoprefixer cli doesn't work at all.

```
 ~/temp/temp $ npx postcss temp.css --use autoprefixer
.d-flex {
  display: flex;
}

a {
  transition: 1s;
}
/*# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLCJzb3VyY2VzIjpbInRlbXAuY3NzIl0sIm5hbWVzIjpbXSwibWFwcGluZ3MiOiJBQUFBO0VBQ0UsY0FBYztDQUNmOztBQUVEO0VBQ0UsZUFBZSxDQUFDLHlCQUF5QjtDQUMxQyIsImZpbGUiOiJ0ZW1wLmNzcyIsInNvdXJjZXNDb250ZW50IjpbIi5kLWZsZXgge1xuICBkaXNwbGF5OiBmbGV4O1xufVxuXG5hIHtcbiAgdHJhbnNpdGlvbjogMXM7IC8qIGl0IHdpbGwgYmUgcHJlZml4ZWQgKi9cbn1cbiJdfQ== */⏎
```

Anyway, I pushed the commit https://github.com/kkweon/emacs-css-autoprefixer/commit/5b4bdb1f40f5b18b56695510db3b1b9a3b94fee6 which will remove only the last sourceMappingURL. 

Still not sure why CLI stopped working.

```
 ~/temp/temp $ postcss --version                        Sat Mar 10 08:34:57 2018

                                      /|\
                                    //   //
                                  //       //
                                //___*___*___//
                              //--*---------*--//
                            /|| *             * ||/
                          // ||*    v5.0.0     *|| //
                        //   || *             * ||   //
                      //_____||___*_________*___||_____//

 ~/temp/temp $ autoprefixer --version           405ms  Sat Mar 10 08:35:03 2018
autoprefixer 8.1.0
 ~/temp/temp $ npx --version                            Sat Mar 10 08:35:11 2018
9.7.1
```

**Comment by kkweon** [comment]
Raised an issue in autoprefixer 
https://github.com/postcss/autoprefixer/issues/999

**Comment by kkweon** [comment]
Thanks again. It's solved now
